### ISSUE TITLE
#import raises PG::NotNullViolation for id field on PostgreSQL

### ISSUE THREAD

**Issue by cspeer** [zdennis/activerecord-import#138]
I recently migrated from MySQL to PostgreSQL and now I'm getting this when using #import:
```
ActiveRecord::StatementInvalid: PG::NotNullViolation: ERROR:  null value in column "id" violates not-null constraint
```

The INSERT-Statement it produces clearly lists id as one of the fields and a NULL value is provided:
```
INSERT INTO "metrics_user_top_list_most_active" ("id","object_id","amount","at","created_at","updated_at","customer_id") VALUES (NULL, ...
```

I'm using activerecord-import 0.5.0 and Rails 4.0.4 so I guess for the id field to be NOT NULL is quite common. Any ideas what's going wrong here?

Thanks,
Chris

**Comment by avishai** [comment]
Any news on this one?

**Comment by tokhi** [comment]
Any updates on this issue? I have the same problem.

**Comment by jkowens** [comment]
@tokhi as @avishai mentioned, it sounds like this is an issue with the MySQL auto-increment primary key column not being properly setup with a sequence in the Postgres database on migration. Can you you try @avishai's queries and report back?

It looks like [PGLoader](https://github.com/dimitri/pgloader) attempts to help with migrations to Postgres.

**Comment by lefty313** [comment]
@avishai Thank your sir it saved my day :+1:

**Comment by coreyward** [comment]
I have this issue with Postgresql as well on a database a table like this:

```sql
CREATE TABLE answers (
    id uuid DEFAULT uuid_generate_v4() NOT NULL,
    answer character varying,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);
```
When AR generates SQL for these records, it simply doesn't specify the `id` column at all. For example: 

```sql
INSERT INTO "answers" ("answer", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"  [["answer", "Yes"], ["created_at", "2016-06-16 04:18:20.508992"], ["updated_at", "2016-06-16 04:18:20.508992"]]
```

Whereas `import` generates the following (abbreviated):

```sql
INSERT INTO "answers" ("id", "answer", "created_at", "updated_at") VALUES (NULL, 'Yes', '2016-06-16 04:14:21.168674', '2016-06-16 04:14:21.168791')
```

**Comment by steventen** [comment]
I just found the same problem as @coreyward  mentioned. 

If the table is using uuid as id, the `import` will fail, with
```
PG::NotNullViolation: ERROR:  null value in column "id" violates not-null constraint
```

I have no idea where the id NULL is generated in the INSERT query? Can anyone point that out?

**Comment by jkowens** [comment]
@steventen the code that makes that happen is here:

https://github.com/zdennis/activerecord-import/blob/master/lib/activerecord-import/import.rb#L381

**Comment by steventen** [comment]
@jabley Thanks for pointing that out. 

I think the issue is the `id` attribute already exists in the record with `nil` when you `new` a record, and there is no mechanism to remove this column if `sequence_name.nil?` or `connection.prefetch_primary_key? == false`. Probably better to add some code about this?

I find a work around for it. So instead of just passing the records, I also pass column_names without the `id` column:
```ruby
columns_without_id = YourModel.column_names.reject { |column| column == 'id' }
import(columns_without_id, records)
```

**Comment by mensfeld** [comment]
+1

**Comment by jkowens** [comment]
@steventen I think this could possibly be fixed if something like the code below was added here: https://github.com/zdennis/activerecord-import/blob/master/lib/activerecord-import/import.rb#L355

```
if column_names.include?(primary_key) && columns_hash[primary_key].type == 'uuid'
  column_names.delete(primary_key)
end
```

If someone could put together a PR with a test that would be awesome! 😉

**Comment by jkowens** [comment]
I've sent up a PR to support uuid primary keys. @steventen if you could review/test that would be appreciated!

**Comment by Adamantish** [comment]
@jkowens Cheers. I'm pointing our gemfile to your branch until this is merged.

**Comment by jkowens** [comment]
I'm going to go ahead and close this issue since it has kind of become a catch all for `PG::NotNullViolation` errors and it seems the issues mentioned have been addressed.

**Comment by jkowens** [comment]
@Adamantish uuid primary key support has been included in the 0.16.0 release.

**Comment by dan-corneanu** [comment]
I am still having this issue with 0.19.1
All my ActiveRecord models use the default primary key configuration and the adapter is tiny_tds connecting to MsSQL. Any idea why it is still happening?

**Comment by jkowens** [comment]
@dan-corneanu SQL Server isn't supported by activerecord-import, but there is an extension that is available. See: https://github.com/keeguon/activerecord-import-sqlserver

**Comment by caifara** [comment]
just to lower the bar somewhat, had the same issue, this migration solved that:

```` ruby
  def change
    tables = ActiveRecord::Base.connection.tables - %w(schema_migrations)

    tables.each do |table_name|
      ActiveRecord::Base.connection.execute("alter sequence #{table_name}_id_seq owned by #{table_name}.id;")
    end
  end
`````

**Comment by sushilprj** [comment]
Thanks @caifara, Just added rescue block if table doesn't id sequence.
 ```
def change
    tables = ActiveRecord::Base.connection.tables - %w(schema_migrations)

    tables.each do |table_name|
      begin
          ActiveRecord::Base.connection.execute("alter sequence #{table_name}_id_seq owned by #{table_name}.id;")
     rescue => e
       p " Error -- #{e}"
     end

    end
  end
```
